// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZDURLvoBNrFThc_-OEMhbRLtkO1EdgqA',
    appId: '1:827904626346:web:5422023f08ca5f44bfcad3',
    messagingSenderId: '827904626346',
    projectId: 'reciperover-36ca0',
    authDomain: 'reciperover-36ca0.firebaseapp.com',
    storageBucket: 'reciperover-36ca0.appspot.com',
    measurementId: 'G-LDZJ2YSPKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM8OpxYhpQp5NW6c_-DvWSR2JBjjLIj2Y',
    appId: '1:827904626346:android:460ae87257709fbbbfcad3',
    messagingSenderId: '827904626346',
    projectId: 'reciperover-36ca0',
    storageBucket: 'reciperover-36ca0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqq929hK1tuipQVX3bnffXMHVtO6vCJcc',
    appId: '1:827904626346:ios:eb951315b8e19924bfcad3',
    messagingSenderId: '827904626346',
    projectId: 'reciperover-36ca0',
    storageBucket: 'reciperover-36ca0.appspot.com',
    iosBundleId: 'com.example.reciperover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqq929hK1tuipQVX3bnffXMHVtO6vCJcc',
    appId: '1:827904626346:ios:eb951315b8e19924bfcad3',
    messagingSenderId: '827904626346',
    projectId: 'reciperover-36ca0',
    storageBucket: 'reciperover-36ca0.appspot.com',
    iosBundleId: 'com.example.reciperover',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZDURLvoBNrFThc_-OEMhbRLtkO1EdgqA',
    appId: '1:827904626346:web:308eaa9d1b3e4463bfcad3',
    messagingSenderId: '827904626346',
    projectId: 'reciperover-36ca0',
    authDomain: 'reciperover-36ca0.firebaseapp.com',
    storageBucket: 'reciperover-36ca0.appspot.com',
    measurementId: 'G-1M27NPFS9N',
  );
}
